parameters:

    assetic.cache.class:  Assetic\Cache\FilesystemCache

services:
    assetic.cache:
          class:        %assetic.cache.class%
          arguments:
              - %assetic.cache_dir%/assets