parameters:
    oro_assetic.twig_extension.class:  Oro\Bundle\AsseticBundle\Twig\AsseticExtension
    oro_assetic.routing_loader.class:  Oro\Bundle\AsseticBundle\Routing\AsseticLoader
    oro_assetic.asset_manager.class:   Oro\Bundle\AsseticBundle\Factory\OroAssetManager
    oro_assetic.controller.class:      Oro\Bundle\AsseticBundle\Controller\AsseticController

services:
    oro_assetic.asset_manager:
          class:        %oro_assetic.asset_manager.class%
          arguments:
              - @assetic.asset_manager
              - @twig

    oro_assetic.twig.extension:
          class:        %oro_assetic.twig_extension.class%
          arguments:
              - @assetic.asset_factory
              - %oro_assetic.assets%
              - @templating.name_parser
              - %assetic.bundles%
          tags:
              - { name: twig.extension }

    oro_assetic.routing_loader:
          class:        %oro_assetic.routing_loader.class%
          arguments:
              - @oro_assetic.asset_manager
          tags:
              - { name: routing.loader }

    oro_assetic.controller:
          class:        %oro_assetic.controller.class%
          arguments:
              - @request
              - @oro_assetic.asset_manager
              - @assetic.cache
              - %assetic.enable_profiler%
          scope: prototype
          calls:
              - [setValueSupplier, [@assetic.value_supplier]]